# CMake generated Testfile for 
# Source directory: E:/setup/develop/eigen/unsupported/test
# Build directory: E:/setup/develop/eigen/compiled/unsupported/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(NonLinearOptimization "NonLinearOptimization")
set_tests_properties(NonLinearOptimization PROPERTIES  LABELS "Unsupported")
add_test(NumericalDiff "NumericalDiff")
set_tests_properties(NumericalDiff PROPERTIES  LABELS "Unsupported")
add_test(autodiff_scalar "autodiff_scalar")
set_tests_properties(autodiff_scalar PROPERTIES  LABELS "Unsupported")
add_test(autodiff "autodiff")
set_tests_properties(autodiff PROPERTIES  LABELS "Unsupported")
add_test(BVH "BVH")
set_tests_properties(BVH PROPERTIES  LABELS "Unsupported")
add_test(matrix_exponential "matrix_exponential")
set_tests_properties(matrix_exponential PROPERTIES  LABELS "Unsupported")
add_test(matrix_function "matrix_function")
set_tests_properties(matrix_function PROPERTIES  LABELS "Unsupported")
add_test(matrix_power "matrix_power")
set_tests_properties(matrix_power PROPERTIES  LABELS "Unsupported")
add_test(matrix_square_root "matrix_square_root")
set_tests_properties(matrix_square_root PROPERTIES  LABELS "Unsupported")
add_test(alignedvector3 "alignedvector3")
set_tests_properties(alignedvector3 PROPERTIES  LABELS "Unsupported")
add_test(FFT "FFT")
set_tests_properties(FFT PROPERTIES  LABELS "Unsupported")
add_test(EulerAngles "EulerAngles")
set_tests_properties(EulerAngles PROPERTIES  LABELS "Unsupported")
add_test(sparse_extra "sparse_extra")
set_tests_properties(sparse_extra PROPERTIES  LABELS "Unsupported")
add_test(polynomialsolver "polynomialsolver")
set_tests_properties(polynomialsolver PROPERTIES  LABELS "Unsupported")
add_test(polynomialutils "polynomialutils")
set_tests_properties(polynomialutils PROPERTIES  LABELS "Unsupported")
add_test(splines "splines")
set_tests_properties(splines PROPERTIES  LABELS "Unsupported")
add_test(gmres "gmres")
set_tests_properties(gmres PROPERTIES  LABELS "Unsupported")
add_test(minres "minres")
set_tests_properties(minres PROPERTIES  LABELS "Unsupported")
add_test(levenberg_marquardt "levenberg_marquardt")
set_tests_properties(levenberg_marquardt PROPERTIES  LABELS "Unsupported")
add_test(kronecker_product "kronecker_product")
set_tests_properties(kronecker_product PROPERTIES  LABELS "Unsupported")
add_test(special_functions "special_functions")
set_tests_properties(special_functions PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_dimension "cxx11_tensor_dimension")
set_tests_properties(cxx11_tensor_dimension PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_map "cxx11_tensor_map")
set_tests_properties(cxx11_tensor_map PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_assign "cxx11_tensor_assign")
set_tests_properties(cxx11_tensor_assign PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_comparisons "cxx11_tensor_comparisons")
set_tests_properties(cxx11_tensor_comparisons PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_forced_eval "cxx11_tensor_forced_eval")
set_tests_properties(cxx11_tensor_forced_eval PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_math "cxx11_tensor_math")
set_tests_properties(cxx11_tensor_math PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_const "cxx11_tensor_const")
set_tests_properties(cxx11_tensor_const PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_intdiv "cxx11_tensor_intdiv")
set_tests_properties(cxx11_tensor_intdiv PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_casts "cxx11_tensor_casts")
set_tests_properties(cxx11_tensor_casts PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_empty "cxx11_tensor_empty")
set_tests_properties(cxx11_tensor_empty PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_sugar "cxx11_tensor_sugar")
set_tests_properties(cxx11_tensor_sugar PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_roundings "cxx11_tensor_roundings")
set_tests_properties(cxx11_tensor_roundings PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_layout_swap "cxx11_tensor_layout_swap")
set_tests_properties(cxx11_tensor_layout_swap PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_io "cxx11_tensor_io")
set_tests_properties(cxx11_tensor_io PROPERTIES  LABELS "Unsupported")
add_test(cxx11_tensor_uint128 "cxx11_tensor_uint128")
set_tests_properties(cxx11_tensor_uint128 PROPERTIES  LABELS "Unsupported")
