# CMake generated Testfile for 
# Source directory: E:/setup/develop/eigen/test
# Build directory: E:/setup/develop/eigen/compiled/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rand "rand")
set_tests_properties(rand PROPERTIES  LABELS "Official")
add_test(meta "meta")
set_tests_properties(meta PROPERTIES  LABELS "Official")
add_test(numext "numext")
set_tests_properties(numext PROPERTIES  LABELS "Official")
add_test(sizeof "sizeof")
set_tests_properties(sizeof PROPERTIES  LABELS "Official")
add_test(dynalloc "dynalloc")
set_tests_properties(dynalloc PROPERTIES  LABELS "Official")
add_test(nomalloc "nomalloc")
set_tests_properties(nomalloc PROPERTIES  LABELS "Official")
add_test(first_aligned "first_aligned")
set_tests_properties(first_aligned PROPERTIES  LABELS "Official")
add_test(nullary "nullary")
set_tests_properties(nullary PROPERTIES  LABELS "Official")
add_test(mixingtypes "mixingtypes")
set_tests_properties(mixingtypes PROPERTIES  LABELS "Official")
add_test(packetmath "packetmath")
set_tests_properties(packetmath PROPERTIES  LABELS "Official")
add_test(unalignedassert "unalignedassert")
set_tests_properties(unalignedassert PROPERTIES  LABELS "Official")
add_test(vectorization_logic "vectorization_logic")
set_tests_properties(vectorization_logic PROPERTIES  LABELS "Official")
add_test(basicstuff "basicstuff")
set_tests_properties(basicstuff PROPERTIES  LABELS "Official")
add_test(constructor "constructor")
set_tests_properties(constructor PROPERTIES  LABELS "Official")
add_test(linearstructure "linearstructure")
set_tests_properties(linearstructure PROPERTIES  LABELS "Official")
add_test(integer_types "integer_types")
set_tests_properties(integer_types PROPERTIES  LABELS "Official")
add_test(unalignedcount "unalignedcount")
set_tests_properties(unalignedcount PROPERTIES  LABELS "Official")
add_test(exceptions "exceptions")
set_tests_properties(exceptions PROPERTIES  LABELS "Official")
add_test(redux "redux")
set_tests_properties(redux PROPERTIES  LABELS "Official")
add_test(visitor "visitor")
set_tests_properties(visitor PROPERTIES  LABELS "Official")
add_test(block "block")
set_tests_properties(block PROPERTIES  LABELS "Official")
add_test(corners "corners")
set_tests_properties(corners PROPERTIES  LABELS "Official")
add_test(swap "swap")
set_tests_properties(swap PROPERTIES  LABELS "Official")
add_test(resize "resize")
set_tests_properties(resize PROPERTIES  LABELS "Official")
add_test(conservative_resize "conservative_resize")
set_tests_properties(conservative_resize PROPERTIES  LABELS "Official")
add_test(product_small "product_small")
set_tests_properties(product_small PROPERTIES  LABELS "Official")
add_test(product_large "product_large")
set_tests_properties(product_large PROPERTIES  LABELS "Official")
add_test(product_extra "product_extra")
set_tests_properties(product_extra PROPERTIES  LABELS "Official")
add_test(diagonalmatrices "diagonalmatrices")
set_tests_properties(diagonalmatrices PROPERTIES  LABELS "Official")
add_test(adjoint "adjoint")
set_tests_properties(adjoint PROPERTIES  LABELS "Official")
add_test(diagonal "diagonal")
set_tests_properties(diagonal PROPERTIES  LABELS "Official")
add_test(miscmatrices "miscmatrices")
set_tests_properties(miscmatrices PROPERTIES  LABELS "Official")
add_test(commainitializer "commainitializer")
set_tests_properties(commainitializer PROPERTIES  LABELS "Official")
add_test(smallvectors "smallvectors")
set_tests_properties(smallvectors PROPERTIES  LABELS "Official")
add_test(mapped_matrix "mapped_matrix")
set_tests_properties(mapped_matrix PROPERTIES  LABELS "Official")
add_test(mapstride "mapstride")
set_tests_properties(mapstride PROPERTIES  LABELS "Official")
add_test(mapstaticmethods "mapstaticmethods")
set_tests_properties(mapstaticmethods PROPERTIES  LABELS "Official")
add_test(array "array")
set_tests_properties(array PROPERTIES  LABELS "Official")
add_test(array_for_matrix "array_for_matrix")
set_tests_properties(array_for_matrix PROPERTIES  LABELS "Official")
add_test(array_replicate "array_replicate")
set_tests_properties(array_replicate PROPERTIES  LABELS "Official")
add_test(array_reverse "array_reverse")
set_tests_properties(array_reverse PROPERTIES  LABELS "Official")
add_test(ref "ref")
set_tests_properties(ref PROPERTIES  LABELS "Official")
add_test(is_same_dense "is_same_dense")
set_tests_properties(is_same_dense PROPERTIES  LABELS "Official")
add_test(triangular "triangular")
set_tests_properties(triangular PROPERTIES  LABELS "Official")
add_test(selfadjoint "selfadjoint")
set_tests_properties(selfadjoint PROPERTIES  LABELS "Official")
add_test(product_selfadjoint "product_selfadjoint")
set_tests_properties(product_selfadjoint PROPERTIES  LABELS "Official")
add_test(product_symm "product_symm")
set_tests_properties(product_symm PROPERTIES  LABELS "Official")
add_test(product_syrk "product_syrk")
set_tests_properties(product_syrk PROPERTIES  LABELS "Official")
add_test(product_trmv "product_trmv")
set_tests_properties(product_trmv PROPERTIES  LABELS "Official")
add_test(product_trmm "product_trmm")
set_tests_properties(product_trmm PROPERTIES  LABELS "Official")
add_test(product_trsolve "product_trsolve")
set_tests_properties(product_trsolve PROPERTIES  LABELS "Official")
add_test(product_mmtr "product_mmtr")
set_tests_properties(product_mmtr PROPERTIES  LABELS "Official")
add_test(product_notemporary "product_notemporary")
set_tests_properties(product_notemporary PROPERTIES  LABELS "Official")
add_test(stable_norm "stable_norm")
set_tests_properties(stable_norm PROPERTIES  LABELS "Official")
add_test(permutationmatrices "permutationmatrices")
set_tests_properties(permutationmatrices PROPERTIES  LABELS "Official")
add_test(bandmatrix "bandmatrix")
set_tests_properties(bandmatrix PROPERTIES  LABELS "Official")
add_test(cholesky "cholesky")
set_tests_properties(cholesky PROPERTIES  LABELS "Official")
add_test(lu "lu")
set_tests_properties(lu PROPERTIES  LABELS "Official")
add_test(determinant "determinant")
set_tests_properties(determinant PROPERTIES  LABELS "Official")
add_test(inverse "inverse")
set_tests_properties(inverse PROPERTIES  LABELS "Official")
add_test(qr "qr")
set_tests_properties(qr PROPERTIES  LABELS "Official")
add_test(qr_colpivoting "qr_colpivoting")
set_tests_properties(qr_colpivoting PROPERTIES  LABELS "Official")
add_test(qr_fullpivoting "qr_fullpivoting")
set_tests_properties(qr_fullpivoting PROPERTIES  LABELS "Official")
add_test(upperbidiagonalization "upperbidiagonalization")
set_tests_properties(upperbidiagonalization PROPERTIES  LABELS "Official")
add_test(hessenberg "hessenberg")
set_tests_properties(hessenberg PROPERTIES  LABELS "Official")
add_test(schur_real "schur_real")
set_tests_properties(schur_real PROPERTIES  LABELS "Official")
add_test(schur_complex "schur_complex")
set_tests_properties(schur_complex PROPERTIES  LABELS "Official")
add_test(eigensolver_selfadjoint "eigensolver_selfadjoint")
set_tests_properties(eigensolver_selfadjoint PROPERTIES  LABELS "Official")
add_test(eigensolver_generic "eigensolver_generic")
set_tests_properties(eigensolver_generic PROPERTIES  LABELS "Official")
add_test(eigensolver_complex "eigensolver_complex")
set_tests_properties(eigensolver_complex PROPERTIES  LABELS "Official")
add_test(real_qz "real_qz")
set_tests_properties(real_qz PROPERTIES  LABELS "Official")
add_test(eigensolver_generalized_real "eigensolver_generalized_real")
set_tests_properties(eigensolver_generalized_real PROPERTIES  LABELS "Official")
add_test(jacobi "jacobi")
set_tests_properties(jacobi PROPERTIES  LABELS "Official")
add_test(jacobisvd "jacobisvd")
set_tests_properties(jacobisvd PROPERTIES  LABELS "Official")
add_test(bdcsvd "bdcsvd")
set_tests_properties(bdcsvd PROPERTIES  LABELS "Official")
add_test(householder "householder")
set_tests_properties(householder PROPERTIES  LABELS "Official")
add_test(geo_orthomethods "geo_orthomethods")
set_tests_properties(geo_orthomethods PROPERTIES  LABELS "Official")
add_test(geo_quaternion "geo_quaternion")
set_tests_properties(geo_quaternion PROPERTIES  LABELS "Official")
add_test(geo_eulerangles "geo_eulerangles")
set_tests_properties(geo_eulerangles PROPERTIES  LABELS "Official")
add_test(geo_parametrizedline "geo_parametrizedline")
set_tests_properties(geo_parametrizedline PROPERTIES  LABELS "Official")
add_test(geo_alignedbox "geo_alignedbox")
set_tests_properties(geo_alignedbox PROPERTIES  LABELS "Official")
add_test(geo_hyperplane "geo_hyperplane")
set_tests_properties(geo_hyperplane PROPERTIES  LABELS "Official")
add_test(geo_transformations "geo_transformations")
set_tests_properties(geo_transformations PROPERTIES  LABELS "Official")
add_test(geo_homogeneous "geo_homogeneous")
set_tests_properties(geo_homogeneous PROPERTIES  LABELS "Official")
add_test(stdvector "stdvector")
set_tests_properties(stdvector PROPERTIES  LABELS "Official")
add_test(stdvector_overload "stdvector_overload")
set_tests_properties(stdvector_overload PROPERTIES  LABELS "Official")
add_test(stdlist "stdlist")
set_tests_properties(stdlist PROPERTIES  LABELS "Official")
add_test(stdlist_overload "stdlist_overload")
set_tests_properties(stdlist_overload PROPERTIES  LABELS "Official")
add_test(stddeque "stddeque")
set_tests_properties(stddeque PROPERTIES  LABELS "Official")
add_test(stddeque_overload "stddeque_overload")
set_tests_properties(stddeque_overload PROPERTIES  LABELS "Official")
add_test(sparse_basic "sparse_basic")
set_tests_properties(sparse_basic PROPERTIES  LABELS "Official")
add_test(sparse_block "sparse_block")
set_tests_properties(sparse_block PROPERTIES  LABELS "Official")
add_test(sparse_vector "sparse_vector")
set_tests_properties(sparse_vector PROPERTIES  LABELS "Official")
add_test(sparse_product "sparse_product")
set_tests_properties(sparse_product PROPERTIES  LABELS "Official")
add_test(sparse_ref "sparse_ref")
set_tests_properties(sparse_ref PROPERTIES  LABELS "Official")
add_test(sparse_solvers "sparse_solvers")
set_tests_properties(sparse_solvers PROPERTIES  LABELS "Official")
add_test(sparse_permutations "sparse_permutations")
set_tests_properties(sparse_permutations PROPERTIES  LABELS "Official")
add_test(simplicial_cholesky "simplicial_cholesky")
set_tests_properties(simplicial_cholesky PROPERTIES  LABELS "Official")
add_test(conjugate_gradient "conjugate_gradient")
set_tests_properties(conjugate_gradient PROPERTIES  LABELS "Official")
add_test(incomplete_cholesky "incomplete_cholesky")
set_tests_properties(incomplete_cholesky PROPERTIES  LABELS "Official")
add_test(bicgstab "bicgstab")
set_tests_properties(bicgstab PROPERTIES  LABELS "Official")
add_test(lscg "lscg")
set_tests_properties(lscg PROPERTIES  LABELS "Official")
add_test(sparselu "sparselu")
set_tests_properties(sparselu PROPERTIES  LABELS "Official")
add_test(sparseqr "sparseqr")
set_tests_properties(sparseqr PROPERTIES  LABELS "Official")
add_test(umeyama "umeyama")
set_tests_properties(umeyama PROPERTIES  LABELS "Official")
add_test(nesting_ops "nesting_ops")
set_tests_properties(nesting_ops PROPERTIES  LABELS "Official")
add_test(zerosized "zerosized")
set_tests_properties(zerosized PROPERTIES  LABELS "Official")
add_test(dontalign "dontalign")
set_tests_properties(dontalign PROPERTIES  LABELS "Official")
add_test(evaluators "evaluators")
set_tests_properties(evaluators PROPERTIES  LABELS "Official")
add_test(sizeoverflow "sizeoverflow")
set_tests_properties(sizeoverflow PROPERTIES  LABELS "Official")
add_test(prec_inverse_4x4 "prec_inverse_4x4")
set_tests_properties(prec_inverse_4x4 PROPERTIES  LABELS "Official")
add_test(vectorwiseop "vectorwiseop")
set_tests_properties(vectorwiseop PROPERTIES  LABELS "Official")
add_test(special_numbers "special_numbers")
set_tests_properties(special_numbers PROPERTIES  LABELS "Official")
add_test(rvalue_types "rvalue_types")
set_tests_properties(rvalue_types PROPERTIES  LABELS "Official")
add_test(dense_storage "dense_storage")
set_tests_properties(dense_storage PROPERTIES  LABELS "Official")
add_test(ctorleak "ctorleak")
set_tests_properties(ctorleak PROPERTIES  LABELS "Official")
add_test(mpl2only "mpl2only")
set_tests_properties(mpl2only PROPERTIES  LABELS "Official")
add_test(inplace_decomposition "inplace_decomposition")
set_tests_properties(inplace_decomposition PROPERTIES  LABELS "Official")
add_test(half_float "half_float")
set_tests_properties(half_float PROPERTIES  LABELS "Official")
add_test(array_of_string "array_of_string")
set_tests_properties(array_of_string PROPERTIES  LABELS "Official")
add_test(fastmath "fastmath")
set_tests_properties(fastmath PROPERTIES  LABELS "Official")
add_test(failtests "D:/Develop/CMake/bin/cmake.exe" "E:/setup/develop/eigen" "-G" "MinGW Makefiles" "-DEIGEN_FAILTEST=ON")
set_tests_properties(failtests PROPERTIES  WORKING_DIRECTORY "E:/setup/develop/eigen/compiled/test/failtests")
